name: "Sonar Cloud Scan"
on:
  workflow_dispatch:

jobs:
  SonarCloudScan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v4.0.0
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
              -Dsonar.organization=PranavTupe
              -Dsonar.projectKey=wine-quality
              -Dsonar.python.coverage.reportPaths=coverage.xml